version: "2.4"

services:
  mongo:
    image: "mongo:4.2.3"
    ports:
        - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    volumes:
        - ./mongodb-data:/data/db
